### PR TITLE
fixes for multiple issues

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/209

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/210

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/212

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/213

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/220

**Comment by bastelfreak** [comment]
https://github.com/DCC-org/documents/issues/221

**Review by Marcellii — APPROVED** [review]

**Pull request merged**
